//------------------------------------------------------------------------------
// <copyright file="XMLNamespaceUserControl.Designer.cs" company="Florian Wolters">
//     Copyright (c) Florian Wolters. All rights reserved.
// </copyright>
// <author>Florian Wolters &lt;wolters.fl@gmail.com&gt;</author>
// <auto-generated/>
//------------------------------------------------------------------------------

namespace FlorianWolters.Windows.Forms.XML.UserControls
{
    partial class XMLNamespaceUserControl
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.ListBox listBoxNamespaces;

        /// <summary>
        /// Releases the unmanaged resources used by this <see cref="XPathUserControl"/> and optionally releases the
        /// managed resources.
        /// </summary>
        /// <param name="disposing">
        /// <c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged
        /// resources.
        /// </param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Vom Komponenten-Designer generierter Code

        /// <summary> 
        /// Erforderliche Methode für die Designerunterstützung. 
        /// Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.Label labelListBox;
            this.listBoxNamespaces = new System.Windows.Forms.ListBox();
            labelListBox = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // labelListBox
            // 
            labelListBox.AutoSize = true;
            labelListBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            labelListBox.Location = new System.Drawing.Point(0, 0);
            labelListBox.Name = "labelListBox";
            labelListBox.Size = new System.Drawing.Size(153, 13);
            labelListBox.TabIndex = 1;
            labelListBox.Text = "Default XML Namespaces";
            // 
            // listBoxNamespaces
            // 
            this.listBoxNamespaces.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.listBoxNamespaces.FormattingEnabled = true;
            this.listBoxNamespaces.Location = new System.Drawing.Point(0, 17);
            this.listBoxNamespaces.Name = "listBoxNamespaces";
            this.listBoxNamespaces.Size = new System.Drawing.Size(240, 95);
            this.listBoxNamespaces.TabIndex = 0;
            this.listBoxNamespaces.SelectedIndexChanged += new System.EventHandler(this.OnSelectedIndexChangedListBox);
            // 
            // XMLNamespaceUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.Controls.Add(labelListBox);
            this.Controls.Add(this.listBoxNamespaces);
            this.Name = "XMLNamespaceUserControl";
            this.Size = new System.Drawing.Size(240, 111);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

    }
}
