//------------------------------------------------------------------------------
// <copyright file="XMLForm.Designer.cs" company="Florian Wolters">
//     Copyright (c) Florian Wolters. All rights reserved.
// </copyright>
// <author>Florian Wolters &lt;wolters.fl@gmail.com&gt;</author>
// <auto-generated/>
//------------------------------------------------------------------------------

namespace FlorianWolters.Windows.Forms.XML.Forms
{
    using FlorianWolters.Windows.Forms.XML.UserControls;

    partial class XMLBrowserForm
    {
        internal XMLDataUserControl xmlDataUserControl;
        internal XMLNamespaceUserControl xmlNamespaceUserControl;
        internal XMLStructureUserControl xmlStructureUserControl;

        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Vom Windows Form-Designer generierter Code

        /// <summary>
        /// Erforderliche Methode für die Designerunterstützung.
        /// Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
        /// </summary>
        private void InitializeComponent()
        {
            this.xPathUserControl = new FlorianWolters.Windows.Forms.XML.UserControls.XPathUserControl();
            this.xmlStructureUserControl = new FlorianWolters.Windows.Forms.XML.UserControls.XMLStructureUserControl();
            this.xmlNamespaceUserControl = new FlorianWolters.Windows.Forms.XML.UserControls.XMLNamespaceUserControl();
            this.xmlDataUserControl = new FlorianWolters.Windows.Forms.XML.UserControls.XMLDataUserControl();
            this.SuspendLayout();
            // 
            // xPathUserControl
            // 
            this.xPathUserControl.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.xPathUserControl.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.xPathUserControl.Location = new System.Drawing.Point(372, 248);
            this.xPathUserControl.Name = "xPathUserControl";
            this.xPathUserControl.Size = new System.Drawing.Size(400, 82);
            this.xPathUserControl.TabIndex = 3;
            // 
            // xmlStructureUserControl
            // 
            this.xmlStructureUserControl.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.xmlStructureUserControl.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.xmlStructureUserControl.Location = new System.Drawing.Point(12, 160);
            this.xmlStructureUserControl.Name = "xmlStructureUserControl";
            this.xmlStructureUserControl.Size = new System.Drawing.Size(340, 389);
            this.xmlStructureUserControl.TabIndex = 2;
            // 
            // xmlNamespaceUserControl
            // 
            this.xmlNamespaceUserControl.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.xmlNamespaceUserControl.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.xmlNamespaceUserControl.Location = new System.Drawing.Point(12, 12);
            this.xmlNamespaceUserControl.Name = "xmlNamespaceUserControl";
            this.xmlNamespaceUserControl.Size = new System.Drawing.Size(760, 142);
            this.xmlNamespaceUserControl.TabIndex = 1;
            // 
            // xmlDataUserControl
            // 
            this.xmlDataUserControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.xmlDataUserControl.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.xmlDataUserControl.Location = new System.Drawing.Point(372, 160);
            this.xmlDataUserControl.Name = "xmlDataUserControl";
            this.xmlDataUserControl.Size = new System.Drawing.Size(400, 82);
            this.xmlDataUserControl.TabIndex = 0;
            // 
            // XMLBrowserForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.xPathUserControl);
            this.Controls.Add(this.xmlStructureUserControl);
            this.Controls.Add(this.xmlNamespaceUserControl);
            this.Controls.Add(this.xmlDataUserControl);
            this.MinimumSize = new System.Drawing.Size(800, 600);
            this.Name = "XMLBrowserForm";
            this.Text = "XML Browser";
            this.ResumeLayout(false);

        }

        #endregion

        private XPathUserControl xPathUserControl;
    }
}

