//------------------------------------------------------------------------------
// <copyright file="CustomXMLPartsForm.Designer.cs" company="Florian Wolters">
//     Copyright (c) Florian Wolters. All rights reserved.
// </copyright>
// <author>Florian Wolters &lt;wolters.fl@gmail.com&gt;</author>
// <auto-generated/>
//------------------------------------------------------------------------------

namespace FlorianWolters.Office.Word.AddIn.CBA.Forms
{
    internal partial class CustomXMLPartsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.listViewCustomXMLParts = new System.Windows.Forms.ListView();
            this.columnHeaderDefaultNamespace = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeaderId = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeaderXML = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.buttonSelectCustomXMLPart = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // listViewCustomXMLParts
            // 
            this.listViewCustomXMLParts.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeaderDefaultNamespace,
            this.columnHeaderId,
            this.columnHeaderXML});
            this.listViewCustomXMLParts.Location = new System.Drawing.Point(13, 13);
            this.listViewCustomXMLParts.Name = "listViewCustomXMLParts";
            this.listViewCustomXMLParts.Size = new System.Drawing.Size(894, 704);
            this.listViewCustomXMLParts.TabIndex = 0;
            this.listViewCustomXMLParts.UseCompatibleStateImageBehavior = false;
            this.listViewCustomXMLParts.View = System.Windows.Forms.View.Details;
            this.listViewCustomXMLParts.SelectedIndexChanged += new System.EventHandler(this.SelectedIndexChanged_ListViewCustomXMLParts);
            // 
            // columnHeaderDefaultNamespace
            // 
            this.columnHeaderDefaultNamespace.Text = "Default Namespace";
            this.columnHeaderDefaultNamespace.Width = 304;
            // 
            // columnHeaderId
            // 
            this.columnHeaderId.Text = "ID";
            this.columnHeaderId.Width = 251;
            // 
            // columnHeaderXML
            // 
            this.columnHeaderXML.Text = "XML";
            this.columnHeaderXML.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.columnHeaderXML.Width = 272;
            // 
            // buttonSelectCustomXMLPart
            // 
            this.buttonSelectCustomXMLPart.Enabled = false;
            this.buttonSelectCustomXMLPart.Location = new System.Drawing.Point(914, 13);
            this.buttonSelectCustomXMLPart.Name = "buttonSelectCustomXMLPart";
            this.buttonSelectCustomXMLPart.Size = new System.Drawing.Size(75, 23);
            this.buttonSelectCustomXMLPart.TabIndex = 1;
            this.buttonSelectCustomXMLPart.Text = "Select";
            this.buttonSelectCustomXMLPart.UseVisualStyleBackColor = true;
            this.buttonSelectCustomXMLPart.Click += new System.EventHandler(this.OnClick_ButtonSelectCustomXMLPart);
            // 
            // CustomXMLPartsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 729);
            this.Controls.Add(this.buttonSelectCustomXMLPart);
            this.Controls.Add(this.listViewCustomXMLParts);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "CustomXMLPartsForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Custom XML Parts";
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListView listViewCustomXMLParts;
        private System.Windows.Forms.ColumnHeader columnHeaderDefaultNamespace;
        private System.Windows.Forms.ColumnHeader columnHeaderXML;
        private System.Windows.Forms.ColumnHeader columnHeaderId;
        private System.Windows.Forms.Button buttonSelectCustomXMLPart;
    }
}