//------------------------------------------------------------------------------
// <copyright file="MarkdownForm.cs" company="Florian Wolters">
//     Copyright (c) Florian Wolters. All rights reserved.
// </copyright>
// <author>Florian Wolters &lt;wolters.fl@gmail.com&gt;</author>
// <auto-generated/>
//------------------------------------------------------------------------------

namespace FlorianWolters.Office.Word.AddIn.CBA.Forms
{
    using System;
    using System.Diagnostics;
    using System.IO;
    using System.Text;
    using System.Windows.Forms;
    using MarkdownSharp;

    public partial class MarkdownForm : Form
    {
        private bool hasNavigated = false;

        private readonly Markdown markdown;

        public MarkdownForm(string fileName)
            : this(fileName, new Markdown())
        {
        }

        public MarkdownForm(string fileName, Markdown markdown) : this()
        {
            this.markdown = markdown;
            this.ChangeDocument(fileName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarkdownForm"/> class.
        /// </summary>
        public MarkdownForm()
        {
            this.InitializeComponent();
            this.markdown = new Markdown();
            this.webBrowser.Navigating += this.OnNavigating;
        }

        /// <summary>
        /// Changes the document to display in this <see cref="MarkdownForm"/>
        /// to the specified file path.
        /// </summary>
        /// <param name="fileName">The file path to the document to display.</param>
        public void ChangeDocument(string filePath)
        {
            string markdownText = File.ReadAllText(filePath);
            string htmlText = this.markdown.Transform(markdownText);

            StringBuilder stringBuilder = new StringBuilder("<style type=\"text/css\">");
            stringBuilder.Append(Environment.NewLine);
            stringBuilder.Append("* { font-family: Arial, \"Helvetica Neue\", Helvetica, sans-serif; }");
            stringBuilder.Append(Environment.NewLine);
            stringBuilder.Append("</style>");
            stringBuilder.Append(Environment.NewLine);
            stringBuilder.Append(htmlText);
            this.webBrowser.DocumentText = stringBuilder.ToString();
        }

        /// <summary>
        /// Changes the title of this <see cref="MarkdownForm"/>.
        /// </summary>
        /// <param name="text">The new title.</param>
        public void ChangeTitle(string text)
        {
            this.Text = text;
        }

        /// <summary>
        /// Raises the <see cref="Navigating"/> event.
        /// <para>
        /// Prevents the opening of links in this <see cref="MarkdownForm"/>.
        /// Instead links are opened in the default web browser.
        /// </para>
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">
        /// A <see cref="WebBrowserNavigatingEventArgs"/> that contains the
        /// event data.
        /// </param>
        /// <remarks>
        /// The source code has been taken from <a
        /// href="http://stackoverflow.com/questions/10927696/webbrowser-control-open-default-browser-on-click-on-link">this</a>
        /// Stack Overflow question.
        /// </remarks>
        private void OnNavigating(object sender, WebBrowserNavigatingEventArgs e)
        {
            if (!this.hasNavigated)
            {
                this.hasNavigated = true;
                return;
            }

            e.Cancel = true;

            ProcessStartInfo startInfo = new ProcessStartInfo
            {
                FileName = e.Url.ToString()
            };

            Process.Start(startInfo);
        }
    }
}
