//------------------------------------------------------------------------------
// <copyright file="Ribbon.Designer.cs" company="Florian Wolters">
//     Copyright (c) Florian Wolters. All rights reserved.
// </copyright>
// <author>Florian Wolters &lt;wolters.fl@gmail.com&gt;</author>
// <auto-generated/>
//------------------------------------------------------------------------------

namespace FlorianWolters.Office.Word.AddIn.CBA
{
    using System.ComponentModel;
    using Microsoft.Office.Tools.Ribbon;

    /// <content>
    /// Contains both auto-generated source code by the Microsoft Visual Studio Designer and essential user source code
    /// to initialize the <see cref="Ribbon"/>.
    /// </content>
    internal partial class Ribbon : Microsoft.Office.Tools.Ribbon.RibbonBase
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="Ribbon"/> class.
        /// </summary>
        public Ribbon() : base(Globals.Factory.GetRibbonFactory())
        {
            this.InitializeComponent();
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing"><c>true</c> if managed resources should be disposed; otherwise, <c>false</c>.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Microsoft.Office.Tools.Ribbon.RibbonMenu menuFieldFormatCapitalization;
            Microsoft.Office.Tools.Ribbon.RibbonMenu menuFieldFormatNumber;
            Microsoft.Office.Tools.Ribbon.RibbonSeparator separatorFieldFormat;
            Microsoft.Office.Tools.Ribbon.RibbonGroup groupReferences;
            Microsoft.Office.Tools.Ribbon.RibbonSeparator separatorFirst;
            Microsoft.Office.Tools.Ribbon.RibbonSeparator separatorSecond;
            Microsoft.Office.Tools.Ribbon.RibbonGroup groupTools;
            Microsoft.Office.Tools.Ribbon.RibbonGroup groupFields;
            Microsoft.Office.Tools.Ribbon.RibbonGroup groupDocumentProperties;
            Microsoft.Office.Tools.Ribbon.RibbonGroup groupView;
            Microsoft.Office.Tools.Ribbon.RibbonDropDownItem ribbonDropDownItemImpl1 = this.Factory.CreateRibbonDropDownItem();
            Microsoft.Office.Tools.Ribbon.RibbonDropDownItem ribbonDropDownItemImpl2 = this.Factory.CreateRibbonDropDownItem();
            Microsoft.Office.Tools.Ribbon.RibbonDropDownItem ribbonDropDownItemImpl3 = this.Factory.CreateRibbonDropDownItem();
            Microsoft.Office.Tools.Ribbon.RibbonGroup groupMiscellaneous;
            Microsoft.Office.Tools.Ribbon.RibbonSeparator separatorThird;
            this.toggleButtonFieldFormatCaps = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatFirstCap = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatUpper = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatLower = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatAlphabetic = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatArabic = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatCardText = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatDollarText = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatHex = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatOrdText = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatOrdinal = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatRoman = this.Factory.CreateRibbonToggleButton();
            this.splitButtonInclude = this.Factory.CreateRibbonSplitButton();
            this.buttonIncludeText = this.Factory.CreateRibbonButton();
            this.buttonIncludePicture = this.Factory.CreateRibbonButton();
            this.buttonUpdateFromSource = this.Factory.CreateRibbonButton();
            this.buttonOpenSourceFile = this.Factory.CreateRibbonButton();
            this.buttonUpdateToSource = this.Factory.CreateRibbonButton();
            this.buttonCompare = this.Factory.CreateRibbonButton();
            this.buttonCompareDocuments = this.Factory.CreateRibbonButton();
            this.buttonBindCustomXMLPart = this.Factory.CreateRibbonButton();
            this.splitButtonFieldInsert = this.Factory.CreateRibbonSplitButton();
            this.buttonInsertEmptyField = this.Factory.CreateRibbonButton();
            this.buttonInsertDateField = this.Factory.CreateRibbonButton();
            this.buttonInsertTimeField = this.Factory.CreateRibbonButton();
            this.buttonInsertListNumField = this.Factory.CreateRibbonButton();
            this.buttonInsertPageField = this.Factory.CreateRibbonButton();
            this.menuFieldFormat = this.Factory.CreateRibbonMenu();
            this.toggleButtonFieldFormatMergeFormat = this.Factory.CreateRibbonToggleButton();
            this.menuFieldAction = this.Factory.CreateRibbonMenu();
            this.buttonFieldUpdate = this.Factory.CreateRibbonButton();
            this.toggleButtonFieldLock = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldShowCode = this.Factory.CreateRibbonToggleButton();
            this.box = this.Factory.CreateRibbonBox();
            this.dropDownCustomDocumentProperties = this.Factory.CreateRibbonDropDown();
            this.checkBoxHideInternal = this.Factory.CreateRibbonCheckBox();
            this.buttonCreateCustomDocumentProperty = this.Factory.CreateRibbonButton();
            this.dropDownFieldShading = this.Factory.CreateRibbonDropDown();
            this.toggleButtonFormFieldShading = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldCodes = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonShowMessages = this.Factory.CreateRibbonToggleButton();
            this.buttonShowAbout = this.Factory.CreateRibbonButton();
            this.buttonShowHelp = this.Factory.CreateRibbonButton();
            this.buttonShowConfiguration = this.Factory.CreateRibbonButton();
            this.tabComponentBasedAuthoring = this.Factory.CreateRibbonTab();
            menuFieldFormatCapitalization = this.Factory.CreateRibbonMenu();
            menuFieldFormatNumber = this.Factory.CreateRibbonMenu();
            separatorFieldFormat = this.Factory.CreateRibbonSeparator();
            groupReferences = this.Factory.CreateRibbonGroup();
            separatorFirst = this.Factory.CreateRibbonSeparator();
            separatorSecond = this.Factory.CreateRibbonSeparator();
            groupTools = this.Factory.CreateRibbonGroup();
            groupFields = this.Factory.CreateRibbonGroup();
            groupDocumentProperties = this.Factory.CreateRibbonGroup();
            groupView = this.Factory.CreateRibbonGroup();
            groupMiscellaneous = this.Factory.CreateRibbonGroup();
            separatorThird = this.Factory.CreateRibbonSeparator();
            groupReferences.SuspendLayout();
            groupTools.SuspendLayout();
            groupFields.SuspendLayout();
            groupDocumentProperties.SuspendLayout();
            this.box.SuspendLayout();
            groupView.SuspendLayout();
            groupMiscellaneous.SuspendLayout();
            this.tabComponentBasedAuthoring.SuspendLayout();
            // 
            // menuFieldFormatCapitalization
            // 
            menuFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatCaps);
            menuFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatFirstCap);
            menuFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatUpper);
            menuFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatLower);
            menuFieldFormatCapitalization.Label = "Capitalization";
            menuFieldFormatCapitalization.Name = "menuFieldFormatCapitalization";
            menuFieldFormatCapitalization.OfficeImageId = "ChangeCaseGallery";
            menuFieldFormatCapitalization.ShowImage = true;
            // 
            // toggleButtonFieldFormatCaps
            // 
            this.toggleButtonFieldFormatCaps.Label = "Uppercase Words";
            this.toggleButtonFieldFormatCaps.Name = "toggleButtonFieldFormatCaps";
            this.toggleButtonFieldFormatCaps.OfficeImageId = "ChangeCaseGallery";
            this.toggleButtonFieldFormatCaps.ScreenTip = "Capitalizes the first letter of each word";
            this.toggleButtonFieldFormatCaps.ShowImage = true;
            this.toggleButtonFieldFormatCaps.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatFirstCap
            // 
            this.toggleButtonFieldFormatFirstCap.Label = "Uppercase First";
            this.toggleButtonFieldFormatFirstCap.Name = "toggleButtonFieldFormatFirstCap";
            this.toggleButtonFieldFormatFirstCap.OfficeImageId = "ChangeCaseGallery";
            this.toggleButtonFieldFormatFirstCap.ScreenTip = "Capitalizes the first letter of the first word";
            this.toggleButtonFieldFormatFirstCap.ShowImage = true;
            this.toggleButtonFieldFormatFirstCap.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatUpper
            // 
            this.toggleButtonFieldFormatUpper.Label = "Uppercase All";
            this.toggleButtonFieldFormatUpper.Name = "toggleButtonFieldFormatUpper";
            this.toggleButtonFieldFormatUpper.OfficeImageId = "ChangeCaseGallery";
            this.toggleButtonFieldFormatUpper.ScreenTip = "Capitalizes all letters";
            this.toggleButtonFieldFormatUpper.ShowImage = true;
            this.toggleButtonFieldFormatUpper.SuperTip = "Has no effect if the entire field is formatted as uppercase letters.";
            this.toggleButtonFieldFormatUpper.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatLower
            // 
            this.toggleButtonFieldFormatLower.Label = "Lowercase All";
            this.toggleButtonFieldFormatLower.Name = "toggleButtonFieldFormatLower";
            this.toggleButtonFieldFormatLower.OfficeImageId = "ChangeCaseGallery";
            this.toggleButtonFieldFormatLower.ScreenTip = "Uncapitalizes all letters";
            this.toggleButtonFieldFormatLower.ShowImage = true;
            this.toggleButtonFieldFormatLower.SuperTip = "Has no effect if the entire field is formatted as lowercase letters.";
            this.toggleButtonFieldFormatLower.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // menuFieldFormatNumber
            // 
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatAlphabetic);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatArabic);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatCardText);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatDollarText);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatHex);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatOrdText);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatOrdinal);
            menuFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatRoman);
            menuFieldFormatNumber.Label = "Number";
            menuFieldFormatNumber.Name = "menuFieldFormatNumber";
            menuFieldFormatNumber.OfficeImageId = "InsertNumberAlternate";
            menuFieldFormatNumber.ShowImage = true;
            // 
            // toggleButtonFieldFormatAlphabetic
            // 
            this.toggleButtonFieldFormatAlphabetic.Label = "Uppercase Alphabetic Characters";
            this.toggleButtonFieldFormatAlphabetic.Name = "toggleButtonFieldFormatAlphabetic";
            this.toggleButtonFieldFormatAlphabetic.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatAlphabetic.ScreenTip = "Displays results as uppercase alphabetic characters, e.g. \"b\"";
            this.toggleButtonFieldFormatAlphabetic.ShowImage = true;
            this.toggleButtonFieldFormatAlphabetic.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatArabic
            // 
            this.toggleButtonFieldFormatArabic.Label = "Arabic Cardinal Numbers";
            this.toggleButtonFieldFormatArabic.Name = "toggleButtonFieldFormatArabic";
            this.toggleButtonFieldFormatArabic.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatArabic.ScreenTip = "Displays results as Arabic cardinal numbers, e.g. \"31\"";
            this.toggleButtonFieldFormatArabic.ShowImage = true;
            this.toggleButtonFieldFormatArabic.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatCardText
            // 
            this.toggleButtonFieldFormatCardText.Label = "Cardinal Text";
            this.toggleButtonFieldFormatCardText.Name = "toggleButtonFieldFormatCardText";
            this.toggleButtonFieldFormatCardText.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatCardText.ScreenTip = "Displays results as cardinal text, e.g. \"seven hundred ninety\"";
            this.toggleButtonFieldFormatCardText.ShowImage = true;
            this.toggleButtonFieldFormatCardText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatDollarText
            // 
            this.toggleButtonFieldFormatDollarText.Label = "Cardinal Text (with fraction)";
            this.toggleButtonFieldFormatDollarText.Name = "toggleButtonFieldFormatDollarText";
            this.toggleButtonFieldFormatDollarText.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatDollarText.ScreenTip = "Displays results as cardinal text, e.g. \"Fourteen and 55/100\"";
            this.toggleButtonFieldFormatDollarText.ShowImage = true;
            this.toggleButtonFieldFormatDollarText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatHex
            // 
            this.toggleButtonFieldFormatHex.Label = "Hexadecimal Numbers";
            this.toggleButtonFieldFormatHex.Name = "toggleButtonFieldFormatHex";
            this.toggleButtonFieldFormatHex.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatHex.ScreenTip = "Displays results as hexadecimal numbers, e.g. \"1CA\"";
            this.toggleButtonFieldFormatHex.ShowImage = true;
            this.toggleButtonFieldFormatHex.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatOrdText
            // 
            this.toggleButtonFieldFormatOrdText.Label = "Ordinal Text";
            this.toggleButtonFieldFormatOrdText.Name = "toggleButtonFieldFormatOrdText";
            this.toggleButtonFieldFormatOrdText.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatOrdText.ScreenTip = "Displays results as ordinal text, e.g. \"twenty-first\"";
            this.toggleButtonFieldFormatOrdText.ShowImage = true;
            this.toggleButtonFieldFormatOrdText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatOrdinal
            // 
            this.toggleButtonFieldFormatOrdinal.Label = "Ordinal Arabic Numerals";
            this.toggleButtonFieldFormatOrdinal.Name = "toggleButtonFieldFormatOrdinal";
            this.toggleButtonFieldFormatOrdinal.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatOrdinal.ScreenTip = "Displays results as ordinal Arabic numerals, e.g. \"30th\"";
            this.toggleButtonFieldFormatOrdinal.ShowImage = true;
            this.toggleButtonFieldFormatOrdinal.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatRoman
            // 
            this.toggleButtonFieldFormatRoman.Label = "Roman Numerals";
            this.toggleButtonFieldFormatRoman.Name = "toggleButtonFieldFormatRoman";
            this.toggleButtonFieldFormatRoman.OfficeImageId = "InsertNumberAlternate";
            this.toggleButtonFieldFormatRoman.ScreenTip = "Displays results as ordinal Roman numerals, e.g. \"XI\"";
            this.toggleButtonFieldFormatRoman.ShowImage = true;
            this.toggleButtonFieldFormatRoman.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // separatorFieldFormat
            // 
            separatorFieldFormat.Name = "separatorFieldFormat";
            // 
            // groupReferences
            // 
            groupReferences.Items.Add(this.splitButtonInclude);
            groupReferences.Items.Add(separatorFirst);
            groupReferences.Items.Add(this.buttonUpdateFromSource);
            groupReferences.Items.Add(this.buttonOpenSourceFile);
            groupReferences.Items.Add(this.buttonUpdateToSource);
            groupReferences.Items.Add(separatorSecond);
            groupReferences.Items.Add(this.buttonCompare);
            groupReferences.Label = "References";
            groupReferences.Name = "groupReferences";
            // 
            // splitButtonInclude
            // 
            this.splitButtonInclude.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.splitButtonInclude.Enabled = false;
            this.splitButtonInclude.Items.Add(this.buttonIncludeText);
            this.splitButtonInclude.Items.Add(this.buttonIncludePicture);
            this.splitButtonInclude.Label = "Include";
            this.splitButtonInclude.Name = "splitButtonInclude";
            this.splitButtonInclude.OfficeImageId = "QuickPartsInsertGallery";
            this.splitButtonInclude.ScreenTip = "Insert a reference to an external document";
            this.splitButtonInclude.SuperTip = "The referenced file is not stored in this document";
            this.splitButtonInclude.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludeText);
            // 
            // buttonIncludeText
            // 
            this.buttonIncludeText.Label = "Include Text";
            this.buttonIncludeText.Name = "buttonIncludeText";
            this.buttonIncludeText.OfficeImageId = "TextFromFileInsert";
            this.buttonIncludeText.ScreenTip = "Insert a reference to an external document";
            this.buttonIncludeText.ShowImage = true;
            this.buttonIncludeText.SuperTip = "The referenced file is not stored in this document";
            this.buttonIncludeText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludeText);
            // 
            // buttonIncludePicture
            // 
            this.buttonIncludePicture.Label = "Include Picture";
            this.buttonIncludePicture.Name = "buttonIncludePicture";
            this.buttonIncludePicture.OfficeImageId = "PictureFromFileInsert";
            this.buttonIncludePicture.ScreenTip = "Insert a reference to a graphics file";
            this.buttonIncludePicture.ShowImage = true;
            this.buttonIncludePicture.SuperTip = "The referenced file is not stored in this document";
            this.buttonIncludePicture.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludePicture);
            // 
            // separatorFirst
            // 
            separatorFirst.Name = "separatorFirst";
            // 
            // buttonUpdateFromSource
            // 
            this.buttonUpdateFromSource.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonUpdateFromSource.Description = "Updated the fields in the current selection.";
            this.buttonUpdateFromSource.Enabled = false;
            this.buttonUpdateFromSource.Label = "Update From Source";
            this.buttonUpdateFromSource.Name = "buttonUpdateFromSource";
            this.buttonUpdateFromSource.OfficeImageId = "Undo";
            this.buttonUpdateFromSource.ShowImage = true;
            this.buttonUpdateFromSource.SuperTip = "Updates the selected reference(s) in this document with the content of the refere" +
    "nced file(s).";
            this.buttonUpdateFromSource.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonUpdateFromSource);
            // 
            // buttonOpenSourceFile
            // 
            this.buttonOpenSourceFile.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonOpenSourceFile.Enabled = false;
            this.buttonOpenSourceFile.Label = "Open Source File";
            this.buttonOpenSourceFile.Name = "buttonOpenSourceFile";
            this.buttonOpenSourceFile.OfficeImageId = "MasterDocumentShow";
            this.buttonOpenSourceFile.ScreenTip = "Open Source File";
            this.buttonOpenSourceFile.ShowImage = true;
            this.buttonOpenSourceFile.SuperTip = "Opens the source file of the selected reference.";
            this.buttonOpenSourceFile.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonOpenSourceFile);
            // 
            // buttonUpdateToSource
            // 
            this.buttonUpdateToSource.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonUpdateToSource.Enabled = false;
            this.buttonUpdateToSource.Label = "Update To Source";
            this.buttonUpdateToSource.Name = "buttonUpdateToSource";
            this.buttonUpdateToSource.OfficeImageId = "Redo";
            this.buttonUpdateToSource.ShowImage = true;
            this.buttonUpdateToSource.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonUpdateToSource);
            // 
            // separatorSecond
            // 
            separatorSecond.Name = "separatorSecond";
            // 
            // buttonCompare
            // 
            this.buttonCompare.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonCompare.Enabled = false;
            this.buttonCompare.Label = "Compare";
            this.buttonCompare.Name = "buttonCompare";
            this.buttonCompare.OfficeImageId = "FileDocumentInspect";
            this.buttonCompare.ScreenTip = "Compares the content of the selected references.";
            this.buttonCompare.ShowImage = true;
            this.buttonCompare.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonCompare);
            // 
            // groupTools
            // 
            groupTools.Items.Add(this.buttonCompareDocuments);
            groupTools.Items.Add(this.buttonBindCustomXMLPart);
            groupTools.Label = "Tools";
            groupTools.Name = "groupTools";
            // 
            // buttonCompareDocuments
            // 
            this.buttonCompareDocuments.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonCompareDocuments.Label = "Compare Documents";
            this.buttonCompareDocuments.Name = "buttonCompareDocuments";
            this.buttonCompareDocuments.OfficeImageId = "ReviewCompareMenu";
            this.buttonCompareDocuments.ShowImage = true;
            this.buttonCompareDocuments.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonCompareDocuments);
            // 
            // buttonBindCustomXMLPart
            // 
            this.buttonBindCustomXMLPart.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonBindCustomXMLPart.Enabled = false;
            this.buttonBindCustomXMLPart.Label = "Bind XML";
            this.buttonBindCustomXMLPart.Name = "buttonBindCustomXMLPart";
            this.buttonBindCustomXMLPart.OfficeImageId = "XmlStructure";
            this.buttonBindCustomXMLPart.ScreenTip = "Binds content from a custom XML part to a content control.";
            this.buttonBindCustomXMLPart.ShowImage = true;
            this.buttonBindCustomXMLPart.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonBindCustomXMLPart);
            // 
            // groupFields
            // 
            groupFields.Items.Add(this.splitButtonFieldInsert);
            groupFields.Items.Add(this.menuFieldFormat);
            groupFields.Items.Add(this.menuFieldAction);
            groupFields.Label = "Fields";
            groupFields.Name = "groupFields";
            // 
            // splitButtonFieldInsert
            // 
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertEmptyField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertDateField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertTimeField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertListNumField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertPageField);
            this.splitButtonFieldInsert.Label = "Insert Field";
            this.splitButtonFieldInsert.Name = "splitButtonFieldInsert";
            this.splitButtonFieldInsert.OfficeImageId = "FieldInsert";
            this.splitButtonFieldInsert.ScreenTip = "Insert Field";
            this.splitButtonFieldInsert.SuperTip = "Inserts a field function at the current selection.";
            this.splitButtonFieldInsert.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_SplitButtonInsertField);
            // 
            // buttonInsertEmptyField
            // 
            this.buttonInsertEmptyField.Label = "Insert empty field";
            this.buttonInsertEmptyField.Name = "buttonInsertEmptyField";
            this.buttonInsertEmptyField.OfficeImageId = "FieldInsert";
            this.buttonInsertEmptyField.ScreenTip = "Inserts an empty field at the current selection";
            this.buttonInsertEmptyField.ShowImage = true;
            this.buttonInsertEmptyField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertEmptyField);
            // 
            // buttonInsertDateField
            // 
            this.buttonInsertDateField.Label = "Insert \"Date\" field";
            this.buttonInsertDateField.Name = "buttonInsertDateField";
            this.buttonInsertDateField.OfficeImageId = "FieldInsert";
            this.buttonInsertDateField.ScreenTip = "Inserts a DATE field at the current selection";
            this.buttonInsertDateField.ShowImage = true;
            this.buttonInsertDateField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertDateField);
            // 
            // buttonInsertTimeField
            // 
            this.buttonInsertTimeField.Label = "Insert \"Time\" field";
            this.buttonInsertTimeField.Name = "buttonInsertTimeField";
            this.buttonInsertTimeField.OfficeImageId = "FieldInsert";
            this.buttonInsertTimeField.ScreenTip = "Inserts a TIME field at the current selection";
            this.buttonInsertTimeField.ShowImage = true;
            this.buttonInsertTimeField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertTimeField);
            // 
            // buttonInsertListNumField
            // 
            this.buttonInsertListNumField.Label = "Insert \"ListNum\" field";
            this.buttonInsertListNumField.Name = "buttonInsertListNumField";
            this.buttonInsertListNumField.OfficeImageId = "FieldInsert";
            this.buttonInsertListNumField.ScreenTip = "Inserts a LISTNUM field at the current selection";
            this.buttonInsertListNumField.ShowImage = true;
            this.buttonInsertListNumField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertListNumField);
            // 
            // buttonInsertPageField
            // 
            this.buttonInsertPageField.Label = "Insert \"Page\" Field";
            this.buttonInsertPageField.Name = "buttonInsertPageField";
            this.buttonInsertPageField.OfficeImageId = "FieldInsert";
            this.buttonInsertPageField.ScreenTip = "Inserts a PAGE field at the current selection";
            this.buttonInsertPageField.ShowImage = true;
            this.buttonInsertPageField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertPageField);
            // 
            // menuFieldFormat
            // 
            this.menuFieldFormat.Enabled = false;
            this.menuFieldFormat.Items.Add(menuFieldFormatCapitalization);
            this.menuFieldFormat.Items.Add(menuFieldFormatNumber);
            this.menuFieldFormat.Items.Add(separatorFieldFormat);
            this.menuFieldFormat.Items.Add(this.toggleButtonFieldFormatMergeFormat);
            this.menuFieldFormat.Label = "Field Format";
            this.menuFieldFormat.Name = "menuFieldFormat";
            this.menuFieldFormat.OfficeImageId = "ChangeStylesMenu";
            this.menuFieldFormat.ShowImage = true;
            // 
            // toggleButtonFieldFormatMergeFormat
            // 
            this.toggleButtonFieldFormatMergeFormat.Label = "Preserve Formatting";
            this.toggleButtonFieldFormatMergeFormat.Name = "toggleButtonFieldFormatMergeFormat";
            this.toggleButtonFieldFormatMergeFormat.OfficeImageId = "FormatPainter";
            this.toggleButtonFieldFormatMergeFormat.ShowImage = true;
            this.toggleButtonFieldFormatMergeFormat.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // menuFieldAction
            // 
            this.menuFieldAction.Enabled = false;
            this.menuFieldAction.Items.Add(this.buttonFieldUpdate);
            this.menuFieldAction.Items.Add(this.toggleButtonFieldLock);
            this.menuFieldAction.Items.Add(this.toggleButtonFieldShowCode);
            this.menuFieldAction.Label = "Field Action";
            this.menuFieldAction.Name = "menuFieldAction";
            this.menuFieldAction.OfficeImageId = "FieldsManage";
            this.menuFieldAction.ShowImage = true;
            // 
            // buttonFieldUpdate
            // 
            this.buttonFieldUpdate.Label = "Update Field";
            this.buttonFieldUpdate.Name = "buttonFieldUpdate";
            this.buttonFieldUpdate.OfficeImageId = "FieldsUpdate";
            this.buttonFieldUpdate.ShowImage = true;
            this.buttonFieldUpdate.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonFieldUpdate);
            // 
            // toggleButtonFieldLock
            // 
            this.toggleButtonFieldLock.Label = "Lock Field";
            this.toggleButtonFieldLock.Name = "toggleButtonFieldLock";
            this.toggleButtonFieldLock.OfficeImageId = "Lock";
            this.toggleButtonFieldLock.ShowImage = true;
            this.toggleButtonFieldLock.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldLock);
            // 
            // toggleButtonFieldShowCode
            // 
            this.toggleButtonFieldShowCode.Label = "Show Field Code";
            this.toggleButtonFieldShowCode.Name = "toggleButtonFieldShowCode";
            this.toggleButtonFieldShowCode.OfficeImageId = "FieldCodes";
            this.toggleButtonFieldShowCode.ScreenTip = "Applies the formatting of the previous result to the new result";
            this.toggleButtonFieldShowCode.ShowImage = true;
            this.toggleButtonFieldShowCode.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldShowCode);
            // 
            // groupDocumentProperties
            // 
            groupDocumentProperties.Items.Add(this.box);
            groupDocumentProperties.Items.Add(this.checkBoxHideInternal);
            groupDocumentProperties.Items.Add(this.buttonCreateCustomDocumentProperty);
            groupDocumentProperties.Label = "Document Properties";
            groupDocumentProperties.Name = "groupDocumentProperties";
            // 
            // box
            // 
            this.box.Items.Add(this.dropDownCustomDocumentProperties);
            this.box.Name = "box";
            // 
            // dropDownCustomDocumentProperties
            // 
            this.dropDownCustomDocumentProperties.Enabled = false;
            this.dropDownCustomDocumentProperties.Label = "Custom Properties";
            this.dropDownCustomDocumentProperties.Name = "dropDownCustomDocumentProperties";
            this.dropDownCustomDocumentProperties.SelectionChanged += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnSelectionChanged_DropDownCustomDocumentProperties);
            // 
            // checkBoxHideInternal
            // 
            this.checkBoxHideInternal.Checked = true;
            this.checkBoxHideInternal.Enabled = false;
            this.checkBoxHideInternal.Label = "Hide \"Internal\"";
            this.checkBoxHideInternal.Name = "checkBoxHideInternal";
            this.checkBoxHideInternal.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_CheckBoxHideInternal);
            // 
            // buttonCreateCustomDocumentProperty
            // 
            this.buttonCreateCustomDocumentProperty.Enabled = false;
            this.buttonCreateCustomDocumentProperty.Label = "Create Custom Document Property";
            this.buttonCreateCustomDocumentProperty.Name = "buttonCreateCustomDocumentProperty";
            this.buttonCreateCustomDocumentProperty.OfficeImageId = "PropertyInsert";
            this.buttonCreateCustomDocumentProperty.ShowImage = true;
            this.buttonCreateCustomDocumentProperty.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonCreateCustomDocumentProperty);
            // 
            // groupView
            // 
            groupView.Items.Add(this.dropDownFieldShading);
            groupView.Items.Add(this.toggleButtonFormFieldShading);
            groupView.Items.Add(this.toggleButtonFieldCodes);
            groupView.Label = "View";
            groupView.Name = "groupView";
            // 
            // dropDownFieldShading
            // 
            this.dropDownFieldShading.Enabled = false;
            ribbonDropDownItemImpl1.Label = "Never";
            ribbonDropDownItemImpl1.ScreenTip = "Never apply on-screen shading for fields. ";
            ribbonDropDownItemImpl1.Tag = "wdFieldShadingNever";
            ribbonDropDownItemImpl2.Label = "Always";
            ribbonDropDownItemImpl2.ScreenTip = "Always apply on-screen shading for fields. ";
            ribbonDropDownItemImpl2.Tag = "wdFieldShadingAlways";
            ribbonDropDownItemImpl3.Label = "When Selected";
            ribbonDropDownItemImpl3.ScreenTip = "Apply on-screen shading only when a fields is selected.";
            ribbonDropDownItemImpl3.Tag = "wdFieldShadingWhenSelected";
            this.dropDownFieldShading.Items.Add(ribbonDropDownItemImpl1);
            this.dropDownFieldShading.Items.Add(ribbonDropDownItemImpl2);
            this.dropDownFieldShading.Items.Add(ribbonDropDownItemImpl3);
            this.dropDownFieldShading.Label = "Field Shading";
            this.dropDownFieldShading.Name = "dropDownFieldShading";
            this.dropDownFieldShading.OfficeImageId = "FieldShading";
            this.dropDownFieldShading.ShowImage = true;
            this.dropDownFieldShading.ShowItemImage = false;
            this.dropDownFieldShading.SelectionChanged += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnSelectionChanged_DropDownFieldShading);
            // 
            // toggleButtonFormFieldShading
            // 
            this.toggleButtonFormFieldShading.Enabled = false;
            this.toggleButtonFormFieldShading.Label = "Form Field Shading";
            this.toggleButtonFormFieldShading.Name = "toggleButtonFormFieldShading";
            this.toggleButtonFormFieldShading.OfficeImageId = "FieldShading";
            this.toggleButtonFormFieldShading.ScreenTip = "Show Form Field Shading";
            this.toggleButtonFormFieldShading.ShowImage = true;
            this.toggleButtonFormFieldShading.SuperTip = "Show Form Field Shading";
            this.toggleButtonFormFieldShading.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFormFieldShading);
            // 
            // toggleButtonFieldCodes
            // 
            this.toggleButtonFieldCodes.Enabled = false;
            this.toggleButtonFieldCodes.Label = "Field Codes";
            this.toggleButtonFieldCodes.Name = "toggleButtonFieldCodes";
            this.toggleButtonFieldCodes.OfficeImageId = "FieldCodes";
            this.toggleButtonFieldCodes.ScreenTip = "Show Field Codes";
            this.toggleButtonFieldCodes.ShowImage = true;
            this.toggleButtonFieldCodes.SuperTip = "Show Field Codes";
            this.toggleButtonFieldCodes.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldCodes);
            // 
            // groupMiscellaneous
            // 
            groupMiscellaneous.Items.Add(this.toggleButtonShowMessages);
            groupMiscellaneous.Items.Add(separatorThird);
            groupMiscellaneous.Items.Add(this.buttonShowAbout);
            groupMiscellaneous.Items.Add(this.buttonShowHelp);
            groupMiscellaneous.Items.Add(this.buttonShowConfiguration);
            groupMiscellaneous.Label = "Miscellaneous";
            groupMiscellaneous.Name = "groupMiscellaneous";
            // 
            // toggleButtonShowMessages
            // 
            this.toggleButtonShowMessages.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.toggleButtonShowMessages.Label = "Messages";
            this.toggleButtonShowMessages.Name = "toggleButtonShowMessages";
            this.toggleButtonShowMessages.OfficeImageId = "CreateReportBlankReport";
            this.toggleButtonShowMessages.ShowImage = true;
            this.toggleButtonShowMessages.SuperTip = "Toggles the visibility of the \"Messages\" window";
            this.toggleButtonShowMessages.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonShowMessagesForm);
            // 
            // separatorThird
            // 
            separatorThird.Name = "separatorThird";
            // 
            // buttonShowAbout
            // 
            this.buttonShowAbout.Label = "About";
            this.buttonShowAbout.Name = "buttonShowAbout";
            this.buttonShowAbout.OfficeImageId = "FileProperties";
            this.buttonShowAbout.ShowImage = true;
            this.buttonShowAbout.SuperTip = "Opens the \"About\" dialog";
            this.buttonShowAbout.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonShowAboutForm);
            // 
            // buttonShowHelp
            // 
            this.buttonShowHelp.Label = "Read Me";
            this.buttonShowHelp.Name = "buttonShowHelp";
            this.buttonShowHelp.OfficeImageId = "WorkflowPending";
            this.buttonShowHelp.ShowImage = true;
            this.buttonShowHelp.SuperTip = "Opens the \"Read Me\" dialog";
            this.buttonShowHelp.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonShowHelpForm);
            // 
            // buttonShowConfiguration
            // 
            this.buttonShowConfiguration.Label = "Configuration";
            this.buttonShowConfiguration.Name = "buttonShowConfiguration";
            this.buttonShowConfiguration.OfficeImageId = "ControlsGallery";
            this.buttonShowConfiguration.ShowImage = true;
            this.buttonShowConfiguration.SuperTip = "Opens the \"Configuration\" dialog";
            this.buttonShowConfiguration.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonShowConfigurationForm);
            // 
            // tabComponentBasedAuthoring
            // 
            this.tabComponentBasedAuthoring.Groups.Add(groupReferences);
            this.tabComponentBasedAuthoring.Groups.Add(groupFields);
            this.tabComponentBasedAuthoring.Groups.Add(groupDocumentProperties);
            this.tabComponentBasedAuthoring.Groups.Add(groupTools);
            this.tabComponentBasedAuthoring.Groups.Add(groupView);
            this.tabComponentBasedAuthoring.Groups.Add(groupMiscellaneous);
            this.tabComponentBasedAuthoring.Label = "Component-Based Authoring";
            this.tabComponentBasedAuthoring.Name = "tabComponentBasedAuthoring";
            // 
            // Ribbon
            // 
            this.Name = "Ribbon";
            this.RibbonType = "Microsoft.Word.Document";
            this.Tabs.Add(this.tabComponentBasedAuthoring);
            this.Load += new Microsoft.Office.Tools.Ribbon.RibbonUIEventHandler(this.OnLoad);
            groupReferences.ResumeLayout(false);
            groupReferences.PerformLayout();
            groupTools.ResumeLayout(false);
            groupTools.PerformLayout();
            groupFields.ResumeLayout(false);
            groupFields.PerformLayout();
            groupDocumentProperties.ResumeLayout(false);
            groupDocumentProperties.PerformLayout();
            this.box.ResumeLayout(false);
            this.box.PerformLayout();
            groupView.ResumeLayout(false);
            groupView.PerformLayout();
            groupMiscellaneous.ResumeLayout(false);
            groupMiscellaneous.PerformLayout();
            this.tabComponentBasedAuthoring.ResumeLayout(false);
            this.tabComponentBasedAuthoring.PerformLayout();

        }

        #endregion

        internal Microsoft.Office.Tools.Ribbon.RibbonTab tabComponentBasedAuthoring;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonCreateCustomDocumentProperty;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonUpdateFromSource;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonUpdateToSource;
        internal Microsoft.Office.Tools.Ribbon.RibbonDropDown dropDownCustomDocumentProperties;
        internal Microsoft.Office.Tools.Ribbon.RibbonCheckBox checkBoxHideInternal;
        internal Microsoft.Office.Tools.Ribbon.RibbonSplitButton splitButtonInclude;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonIncludeText;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonIncludePicture;
        internal Microsoft.Office.Tools.Ribbon.RibbonBox box;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonOpenSourceFile;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertEmptyField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertDateField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertTimeField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertListNumField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertPageField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonShowAbout;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonShowHelp;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton toggleButtonFieldCodes;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton toggleButtonFormFieldShading;
        internal Microsoft.Office.Tools.Ribbon.RibbonDropDown dropDownFieldShading;
        internal RibbonButton buttonCompare;
        internal RibbonButton buttonShowConfiguration;
        internal RibbonButton buttonBindCustomXMLPart;
        internal RibbonButton buttonCompareDocuments;
        internal RibbonToggleButton toggleButtonShowMessages;
        internal RibbonToggleButton toggleButtonFieldFormatCaps;
        internal RibbonToggleButton toggleButtonFieldFormatFirstCap;
        internal RibbonToggleButton toggleButtonFieldFormatUpper;
        internal RibbonToggleButton toggleButtonFieldFormatLower;
        internal RibbonToggleButton toggleButtonFieldFormatAlphabetic;
        internal RibbonToggleButton toggleButtonFieldFormatArabic;
        internal RibbonToggleButton toggleButtonFieldFormatCardText;
        internal RibbonToggleButton toggleButtonFieldFormatDollarText;
        internal RibbonToggleButton toggleButtonFieldFormatHex;
        internal RibbonToggleButton toggleButtonFieldFormatOrdText;
        internal RibbonToggleButton toggleButtonFieldFormatOrdinal;
        internal RibbonToggleButton toggleButtonFieldFormatRoman;
        internal RibbonToggleButton toggleButtonFieldFormatMergeFormat;
        internal RibbonButton buttonFieldUpdate;
        internal RibbonToggleButton toggleButtonFieldLock;
        internal RibbonToggleButton toggleButtonFieldShowCode;
        internal RibbonSplitButton splitButtonFieldInsert;
        internal RibbonMenu menuFieldFormat;
        internal RibbonMenu menuFieldAction;
    }

    /// <summary>
    /// The class <see cref="ThisRibbonCollection"/> contains all <see cref="Ribbon"/>s of the application.
    /// </summary>
    partial class ThisRibbonCollection
    {
        /// <summary>
        /// Gets the <see cref="Ribbon"/>.
        /// </summary>
        internal Ribbon ThisRibbon
        {
            get { return this.GetRibbon<Ribbon>(); }
        }
    }
}
