//------------------------------------------------------------------------------
// <copyright file="Ribbon.Designer.cs" company="Florian Wolters">
//     Copyright (c) Florian Wolters. All rights reserved.
// </copyright>
// <author>Florian Wolters &lt;wolters.fl@gmail.com&gt;</author>
// <auto-generated/>
//------------------------------------------------------------------------------

namespace FlorianWolters.Office.Word.AddIn.CBA
{
    using System.ComponentModel;
    using System.Windows.Forms;
    using FlorianWolters.Office.Word.AddIn.CBA.Forms;
    using Microsoft.Office.Tools.Ribbon;
    using NLog;

    /// <content>
    /// Contains both auto-generated source code by the Microsoft Visual Studio
    /// Designer and essential user source code to initialize the <see
    /// cref="Ribbon"/>.
    /// </content>
    internal partial class Ribbon : Microsoft.Office.Tools.Ribbon.RibbonBase
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary>
        /// The <see cref="Logger"/> for the class <see cref="Ribbon"/>.
        /// </summary>
        private readonly Logger logger;

        /// <summary>
        /// The <see cref="Form"/> whose <see cref="RichTextBox"/> is utilized
        /// as a target by <see cref="NLog"/>.
        /// </summary>
        private readonly Form messagesForm;

        /// <summary>
        /// Initializes a new instance of the <see cref="Ribbon"/> class.
        /// </summary>
        public Ribbon() : base(Globals.Factory.GetRibbonFactory())
        {
            this.InitializeComponent();

            // ATTENTION: The first NLog logger MUST created AFTER the Form with
            // the RichTextBox that should be utilized for logging. In addition,
            // the Form has to be displayed for the first time BEFORE the first
            // NLog logger is created. Sadly, there doesn't exist a Form event
            // for that use case. The "earliest" event is "Form.Load", which
            // occurs before a form is displayed for the first time.

            // Therefore we do have to workaround the problem:
            // 1. Make the Form invisible.
            // 2. Toogle the visibility of the Form (to initialize its controls).
            // 3. Restore the default opacity of the Form.
            this.messagesForm = new MessagesForm();
            double defaultOpacity = this.messagesForm.Opacity;
            this.messagesForm.Opacity = 0d;
            this.messagesForm.Visible = true;
            this.messagesForm.Visible = false;
            this.messagesForm.Opacity = defaultOpacity;

            this.logger = LogManager.GetCurrentClassLogger();
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing"><c>true</c> if managed resources should be disposed; otherwise, <c>false</c>.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Microsoft.Office.Tools.Ribbon.RibbonDropDownItem ribbonDropDownItemImpl1 = this.Factory.CreateRibbonDropDownItem();
            Microsoft.Office.Tools.Ribbon.RibbonDropDownItem ribbonDropDownItemImpl2 = this.Factory.CreateRibbonDropDownItem();
            Microsoft.Office.Tools.Ribbon.RibbonDropDownItem ribbonDropDownItemImpl3 = this.Factory.CreateRibbonDropDownItem();
            this.tabComponentBasedAuthoring = this.Factory.CreateRibbonTab();
            this.groupReferences = this.Factory.CreateRibbonGroup();
            this.splitButtonInclude = this.Factory.CreateRibbonSplitButton();
            this.buttonIncludeText = this.Factory.CreateRibbonButton();
            this.buttonIncludePicture = this.Factory.CreateRibbonButton();
            this.buttonIncludeObject = this.Factory.CreateRibbonButton();
            this.separatorFirst = this.Factory.CreateRibbonSeparator();
            this.buttonUpdateFromSource = this.Factory.CreateRibbonButton();
            this.buttonOpenSourceFile = this.Factory.CreateRibbonButton();
            this.buttonUpdateToSource = this.Factory.CreateRibbonButton();
            this.separatorSecond = this.Factory.CreateRibbonSeparator();
            this.buttonCheckReferences = this.Factory.CreateRibbonButton();
            this.groupTools = this.Factory.CreateRibbonGroup();
            this.buttonCompareDocuments = this.Factory.CreateRibbonButton();
            this.toggleButtonShowMessagesForm = this.Factory.CreateRibbonToggleButton();
            this.groupFields = this.Factory.CreateRibbonGroup();
            this.splitButtonFieldInsert = this.Factory.CreateRibbonSplitButton();
            this.buttonInsertEmptyField = this.Factory.CreateRibbonButton();
            this.buttonInsertDateField = this.Factory.CreateRibbonButton();
            this.buttonInsertTimeField = this.Factory.CreateRibbonButton();
            this.buttonInsertListNumField = this.Factory.CreateRibbonButton();
            this.buttonInsertPageField = this.Factory.CreateRibbonButton();
            this.splitButtonFieldAction = this.Factory.CreateRibbonSplitButton();
            this.buttonFieldUpdate = this.Factory.CreateRibbonButton();
            this.toggleButtonFieldLock = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonShowFieldCode = this.Factory.CreateRibbonToggleButton();
            this.splitButtonFieldFormat = this.Factory.CreateRibbonSplitButton();
            this.splitButtonFieldFormatCapitalization = this.Factory.CreateRibbonSplitButton();
            this.toggleButtonFieldFormatCaps = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatFirstCap = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatUpper = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatLower = this.Factory.CreateRibbonToggleButton();
            this.splitButtonFieldFormatNumber = this.Factory.CreateRibbonSplitButton();
            this.toggleButtonFieldFormatAlphabetic = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatArabic = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatCardText = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatDollarText = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatHex = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatOrdText = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatOrdinal = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatRoman = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonFieldFormatMergeFormat = this.Factory.CreateRibbonToggleButton();
            this.groupDocumentProperties = this.Factory.CreateRibbonGroup();
            this.box = this.Factory.CreateRibbonBox();
            this.dropDownCustomDocumentProperties = this.Factory.CreateRibbonDropDown();
            this.checkBoxHideInternal = this.Factory.CreateRibbonCheckBox();
            this.buttonCreateCustomDocumentProperty = this.Factory.CreateRibbonButton();
            this.buttonBindCustomXMLPart = this.Factory.CreateRibbonButton();
            this.groupView = this.Factory.CreateRibbonGroup();
            this.dropDownFieldShading = this.Factory.CreateRibbonDropDown();
            this.toggleButtonShowFieldShading = this.Factory.CreateRibbonToggleButton();
            this.toggleButtonShowFieldCodes = this.Factory.CreateRibbonToggleButton();
            this.groupMiscellaneous = this.Factory.CreateRibbonGroup();
            this.buttonShowAboutForm = this.Factory.CreateRibbonButton();
            this.buttonShowHelpForm = this.Factory.CreateRibbonButton();
            this.buttonShowConfigurationForm = this.Factory.CreateRibbonButton();
            this.tabComponentBasedAuthoring.SuspendLayout();
            this.groupReferences.SuspendLayout();
            this.groupTools.SuspendLayout();
            this.groupFields.SuspendLayout();
            this.groupDocumentProperties.SuspendLayout();
            this.box.SuspendLayout();
            this.groupView.SuspendLayout();
            this.groupMiscellaneous.SuspendLayout();
            // 
            // tabComponentBasedAuthoring
            // 
            this.tabComponentBasedAuthoring.Groups.Add(this.groupReferences);
            this.tabComponentBasedAuthoring.Groups.Add(this.groupTools);
            this.tabComponentBasedAuthoring.Groups.Add(this.groupFields);
            this.tabComponentBasedAuthoring.Groups.Add(this.groupDocumentProperties);
            this.tabComponentBasedAuthoring.Groups.Add(this.groupView);
            this.tabComponentBasedAuthoring.Groups.Add(this.groupMiscellaneous);
            this.tabComponentBasedAuthoring.Label = "Component-Based Authoring";
            this.tabComponentBasedAuthoring.Name = "tabComponentBasedAuthoring";
            // 
            // groupReferences
            // 
            this.groupReferences.Items.Add(this.splitButtonInclude);
            this.groupReferences.Items.Add(this.separatorFirst);
            this.groupReferences.Items.Add(this.buttonUpdateFromSource);
            this.groupReferences.Items.Add(this.buttonOpenSourceFile);
            this.groupReferences.Items.Add(this.buttonUpdateToSource);
            this.groupReferences.Items.Add(this.separatorSecond);
            this.groupReferences.Items.Add(this.buttonCheckReferences);
            this.groupReferences.Label = "References";
            this.groupReferences.Name = "groupReferences";
            // 
            // splitButtonInclude
            // 
            this.splitButtonInclude.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.splitButtonInclude.Enabled = false;
            this.splitButtonInclude.Items.Add(this.buttonIncludeText);
            this.splitButtonInclude.Items.Add(this.buttonIncludePicture);
            this.splitButtonInclude.Items.Add(this.buttonIncludeObject);
            this.splitButtonInclude.Label = "Include";
            this.splitButtonInclude.Name = "splitButtonInclude";
            this.splitButtonInclude.OfficeImageId = "QuickPartsInsertGallery";
            this.splitButtonInclude.ScreenTip = "Include a reference to another file";
            this.splitButtonInclude.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludeText);
            // 
            // buttonIncludeText
            // 
            this.buttonIncludeText.Label = "Include Text";
            this.buttonIncludeText.Name = "buttonIncludeText";
            this.buttonIncludeText.OfficeImageId = "TextFromFileInsert";
            this.buttonIncludeText.ShowImage = true;
            this.buttonIncludeText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludeText);
            // 
            // buttonIncludePicture
            // 
            this.buttonIncludePicture.Label = "Include Picture";
            this.buttonIncludePicture.Name = "buttonIncludePicture";
            this.buttonIncludePicture.OfficeImageId = "PictureFromFileInsert";
            this.buttonIncludePicture.ShowImage = true;
            this.buttonIncludePicture.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludePicture);
            // 
            // buttonIncludeObject
            // 
            this.buttonIncludeObject.Label = "Include Object";
            this.buttonIncludeObject.Name = "buttonIncludeObject";
            this.buttonIncludeObject.OfficeImageId = "OleObjectctInsert";
            this.buttonIncludeObject.ShowImage = true;
            this.buttonIncludeObject.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonIncludeObject);
            // 
            // separatorFirst
            // 
            this.separatorFirst.Name = "separatorFirst";
            // 
            // buttonUpdateFromSource
            // 
            this.buttonUpdateFromSource.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonUpdateFromSource.Description = "Updated the fields in the current selection.";
            this.buttonUpdateFromSource.Enabled = false;
            this.buttonUpdateFromSource.Label = "Update From Source";
            this.buttonUpdateFromSource.Name = "buttonUpdateFromSource";
            this.buttonUpdateFromSource.OfficeImageId = "Undo";
            this.buttonUpdateFromSource.ShowImage = true;
            this.buttonUpdateFromSource.SuperTip = "Updates the selected reference(s) in this document with the content of the refere" +
    "nced file(s).";
            this.buttonUpdateFromSource.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonUpdateFromSource);
            // 
            // buttonOpenSourceFile
            // 
            this.buttonOpenSourceFile.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonOpenSourceFile.Enabled = false;
            this.buttonOpenSourceFile.Label = "Open Source File";
            this.buttonOpenSourceFile.Name = "buttonOpenSourceFile";
            this.buttonOpenSourceFile.OfficeImageId = "MasterDocumentShow";
            this.buttonOpenSourceFile.ScreenTip = "Open Source File";
            this.buttonOpenSourceFile.ShowImage = true;
            this.buttonOpenSourceFile.SuperTip = "Opens the source file of the selected reference.";
            this.buttonOpenSourceFile.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonOpenSourceFile);
            // 
            // buttonUpdateToSource
            // 
            this.buttonUpdateToSource.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonUpdateToSource.Enabled = false;
            this.buttonUpdateToSource.Label = "Update To Source";
            this.buttonUpdateToSource.Name = "buttonUpdateToSource";
            this.buttonUpdateToSource.OfficeImageId = "Redo";
            this.buttonUpdateToSource.ShowImage = true;
            this.buttonUpdateToSource.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonUpdateToSource);
            // 
            // separatorSecond
            // 
            this.separatorSecond.Name = "separatorSecond";
            // 
            // buttonCheckReferences
            // 
            this.buttonCheckReferences.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonCheckReferences.Label = "Check";
            this.buttonCheckReferences.Name = "buttonCheckReferences";
            this.buttonCheckReferences.OfficeImageId = "FileDocumentInspect";
            this.buttonCheckReferences.ShowImage = true;
            this.buttonCheckReferences.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonCheckReferences);
            // 
            // groupTools
            // 
            this.groupTools.Items.Add(this.buttonCompareDocuments);
            this.groupTools.Items.Add(this.buttonBindCustomXMLPart);
            this.groupTools.Label = "Tools";
            this.groupTools.Name = "groupTools";
            // 
            // buttonCompareDocuments
            // 
            this.buttonCompareDocuments.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonCompareDocuments.Label = "Compare Documents";
            this.buttonCompareDocuments.Name = "buttonCompareDocuments";
            this.buttonCompareDocuments.OfficeImageId = "ReviewCompareMenu";
            this.buttonCompareDocuments.ShowImage = true;
            this.buttonCompareDocuments.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonCompareDocuments);
            // 
            // toggleButtonShowMessagesForm
            // 
            this.toggleButtonShowMessagesForm.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.toggleButtonShowMessagesForm.Label = "Show Messages";
            this.toggleButtonShowMessagesForm.Name = "toggleButtonShowMessagesForm";
            this.toggleButtonShowMessagesForm.OfficeImageId = "CreateReportBlankReport";
            this.toggleButtonShowMessagesForm.ShowImage = true;
            this.toggleButtonShowMessagesForm.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonShowMessagesForm);
            // 
            // groupFields
            // 
            this.groupFields.Items.Add(this.splitButtonFieldInsert);
            this.groupFields.Items.Add(this.splitButtonFieldAction);
            this.groupFields.Items.Add(this.splitButtonFieldFormat);
            this.groupFields.Label = "Fields";
            this.groupFields.Name = "groupFields";
            // 
            // splitButtonFieldInsert
            // 
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertEmptyField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertDateField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertTimeField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertListNumField);
            this.splitButtonFieldInsert.Items.Add(this.buttonInsertPageField);
            this.splitButtonFieldInsert.Label = "Insert Field";
            this.splitButtonFieldInsert.Name = "splitButtonFieldInsert";
            this.splitButtonFieldInsert.OfficeImageId = "FieldInsert";
            this.splitButtonFieldInsert.ScreenTip = "Insert Field";
            this.splitButtonFieldInsert.SuperTip = "Inserts a field function at the current selection.";
            this.splitButtonFieldInsert.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_SplitButtonInsertField);
            // 
            // buttonInsertEmptyField
            // 
            this.buttonInsertEmptyField.Label = "Insert empty field";
            this.buttonInsertEmptyField.Name = "buttonInsertEmptyField";
            this.buttonInsertEmptyField.ShowImage = true;
            this.buttonInsertEmptyField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertEmptyField);
            // 
            // buttonInsertDateField
            // 
            this.buttonInsertDateField.Label = "Insert \"Date\" field";
            this.buttonInsertDateField.Name = "buttonInsertDateField";
            this.buttonInsertDateField.ShowImage = true;
            this.buttonInsertDateField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertDateField);
            // 
            // buttonInsertTimeField
            // 
            this.buttonInsertTimeField.Label = "Insert \"Time\" field";
            this.buttonInsertTimeField.Name = "buttonInsertTimeField";
            this.buttonInsertTimeField.ShowImage = true;
            this.buttonInsertTimeField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertTimeField);
            // 
            // buttonInsertListNumField
            // 
            this.buttonInsertListNumField.Label = "Insert \"ListNum\" field";
            this.buttonInsertListNumField.Name = "buttonInsertListNumField";
            this.buttonInsertListNumField.ShowImage = true;
            this.buttonInsertListNumField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertListNumField);
            // 
            // buttonInsertPageField
            // 
            this.buttonInsertPageField.Label = "Insert \"Page\" Field";
            this.buttonInsertPageField.Name = "buttonInsertPageField";
            this.buttonInsertPageField.ShowImage = true;
            this.buttonInsertPageField.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonInsertPageField);
            // 
            // splitButtonFieldAction
            // 
            this.splitButtonFieldAction.Enabled = false;
            this.splitButtonFieldAction.Items.Add(this.buttonFieldUpdate);
            this.splitButtonFieldAction.Items.Add(this.toggleButtonFieldLock);
            this.splitButtonFieldAction.Items.Add(this.toggleButtonShowFieldCode);
            this.splitButtonFieldAction.Label = "Field Action";
            this.splitButtonFieldAction.Name = "splitButtonFieldAction";
            // 
            // buttonFieldUpdate
            // 
            this.buttonFieldUpdate.Label = "Update Field";
            this.buttonFieldUpdate.Name = "buttonFieldUpdate";
            this.buttonFieldUpdate.ShowImage = true;
            this.buttonFieldUpdate.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonFieldUpdate);
            // 
            // toggleButtonFieldLock
            // 
            this.toggleButtonFieldLock.Label = "Lock Field";
            this.toggleButtonFieldLock.Name = "toggleButtonFieldLock";
            this.toggleButtonFieldLock.ShowImage = true;
            this.toggleButtonFieldLock.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldLock);
            // 
            // toggleButtonShowFieldCode
            // 
            this.toggleButtonShowFieldCode.Label = "Show Field Code";
            this.toggleButtonShowFieldCode.Name = "toggleButtonShowFieldCode";
            this.toggleButtonShowFieldCode.ShowImage = true;
            this.toggleButtonShowFieldCode.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonShowFieldCode);
            // 
            // splitButtonFieldFormat
            // 
            this.splitButtonFieldFormat.Items.Add(this.splitButtonFieldFormatCapitalization);
            this.splitButtonFieldFormat.Items.Add(this.splitButtonFieldFormatNumber);
            this.splitButtonFieldFormat.Items.Add(this.toggleButtonFieldFormatMergeFormat);
            this.splitButtonFieldFormat.Label = "Field Format";
            this.splitButtonFieldFormat.Name = "splitButtonFieldFormat";
            // 
            // splitButtonFieldFormatCapitalization
            // 
            this.splitButtonFieldFormatCapitalization.Enabled = false;
            this.splitButtonFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatCaps);
            this.splitButtonFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatFirstCap);
            this.splitButtonFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatUpper);
            this.splitButtonFieldFormatCapitalization.Items.Add(this.toggleButtonFieldFormatLower);
            this.splitButtonFieldFormatCapitalization.Label = "Capitalization";
            this.splitButtonFieldFormatCapitalization.Name = "splitButtonFieldFormatCapitalization";
            // 
            // toggleButtonFieldFormatCaps
            // 
            this.toggleButtonFieldFormatCaps.Label = "Uppercase Words";
            this.toggleButtonFieldFormatCaps.Name = "toggleButtonFieldFormatCaps";
            this.toggleButtonFieldFormatCaps.ShowImage = true;
            this.toggleButtonFieldFormatCaps.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatFirstCap
            // 
            this.toggleButtonFieldFormatFirstCap.Label = "Uppercase First";
            this.toggleButtonFieldFormatFirstCap.Name = "toggleButtonFieldFormatFirstCap";
            this.toggleButtonFieldFormatFirstCap.ShowImage = true;
            this.toggleButtonFieldFormatFirstCap.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatUpper
            // 
            this.toggleButtonFieldFormatUpper.Label = "Uppercase All";
            this.toggleButtonFieldFormatUpper.Name = "toggleButtonFieldFormatUpper";
            this.toggleButtonFieldFormatUpper.ShowImage = true;
            this.toggleButtonFieldFormatUpper.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatLower
            // 
            this.toggleButtonFieldFormatLower.Label = "Lowercase All";
            this.toggleButtonFieldFormatLower.Name = "toggleButtonFieldFormatLower";
            this.toggleButtonFieldFormatLower.ShowImage = true;
            this.toggleButtonFieldFormatLower.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // splitButtonFieldFormatNumber
            // 
            this.splitButtonFieldFormatNumber.Enabled = false;
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatAlphabetic);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatArabic);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatCardText);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatDollarText);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatHex);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatOrdText);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatOrdinal);
            this.splitButtonFieldFormatNumber.Items.Add(this.toggleButtonFieldFormatRoman);
            this.splitButtonFieldFormatNumber.Label = "Number";
            this.splitButtonFieldFormatNumber.Name = "splitButtonFieldFormatNumber";
            // 
            // toggleButtonFieldFormatAlphabetic
            // 
            this.toggleButtonFieldFormatAlphabetic.Label = "Alphabetic Characters";
            this.toggleButtonFieldFormatAlphabetic.Name = "toggleButtonFieldFormatAlphabetic";
            this.toggleButtonFieldFormatAlphabetic.ShowImage = true;
            this.toggleButtonFieldFormatAlphabetic.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatArabic
            // 
            this.toggleButtonFieldFormatArabic.Label = "Arabic Cardinal Numbers";
            this.toggleButtonFieldFormatArabic.Name = "toggleButtonFieldFormatArabic";
            this.toggleButtonFieldFormatArabic.ShowImage = true;
            this.toggleButtonFieldFormatArabic.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatCardText
            // 
            this.toggleButtonFieldFormatCardText.Label = "Cardinal Text";
            this.toggleButtonFieldFormatCardText.Name = "toggleButtonFieldFormatCardText";
            this.toggleButtonFieldFormatCardText.ShowImage = true;
            this.toggleButtonFieldFormatCardText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatDollarText
            // 
            this.toggleButtonFieldFormatDollarText.Label = "Cardinal Text (with fraction)";
            this.toggleButtonFieldFormatDollarText.Name = "toggleButtonFieldFormatDollarText";
            this.toggleButtonFieldFormatDollarText.ShowImage = true;
            this.toggleButtonFieldFormatDollarText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatHex
            // 
            this.toggleButtonFieldFormatHex.Label = "Hexadecimal Numbers";
            this.toggleButtonFieldFormatHex.Name = "toggleButtonFieldFormatHex";
            this.toggleButtonFieldFormatHex.ShowImage = true;
            this.toggleButtonFieldFormatHex.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatOrdText
            // 
            this.toggleButtonFieldFormatOrdText.Label = "Ordinal Text";
            this.toggleButtonFieldFormatOrdText.Name = "toggleButtonFieldFormatOrdText";
            this.toggleButtonFieldFormatOrdText.ShowImage = true;
            this.toggleButtonFieldFormatOrdText.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatOrdinal
            // 
            this.toggleButtonFieldFormatOrdinal.Label = "Ordinal Ararbic Numerals";
            this.toggleButtonFieldFormatOrdinal.Name = "toggleButtonFieldFormatOrdinal";
            this.toggleButtonFieldFormatOrdinal.ShowImage = true;
            this.toggleButtonFieldFormatOrdinal.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatRoman
            // 
            this.toggleButtonFieldFormatRoman.Label = "Roman Numerals";
            this.toggleButtonFieldFormatRoman.Name = "toggleButtonFieldFormatRoman";
            this.toggleButtonFieldFormatRoman.ShowImage = true;
            this.toggleButtonFieldFormatRoman.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // toggleButtonFieldFormatMergeFormat
            // 
            this.toggleButtonFieldFormatMergeFormat.Label = "Preserve Formatting";
            this.toggleButtonFieldFormatMergeFormat.Name = "toggleButtonFieldFormatMergeFormat";
            this.toggleButtonFieldFormatMergeFormat.ShowImage = true;
            this.toggleButtonFieldFormatMergeFormat.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonFieldFormat);
            // 
            // groupDocumentProperties
            // 
            this.groupDocumentProperties.Items.Add(this.box);
            this.groupDocumentProperties.Items.Add(this.checkBoxHideInternal);
            this.groupDocumentProperties.Items.Add(this.buttonCreateCustomDocumentProperty);
            this.groupDocumentProperties.Label = "Document Properties";
            this.groupDocumentProperties.Name = "groupDocumentProperties";
            // 
            // box
            // 
            this.box.Items.Add(this.dropDownCustomDocumentProperties);
            this.box.Name = "box";
            // 
            // dropDownCustomDocumentProperties
            // 
            this.dropDownCustomDocumentProperties.Label = "Custom Properties";
            this.dropDownCustomDocumentProperties.Name = "dropDownCustomDocumentProperties";
            this.dropDownCustomDocumentProperties.SelectionChanged += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnSelectionChanged_DropDownCustomDocumentProperties);
            // 
            // checkBoxHideInternal
            // 
            this.checkBoxHideInternal.Checked = true;
            this.checkBoxHideInternal.Label = "Hide \"Internal\"";
            this.checkBoxHideInternal.Name = "checkBoxHideInternal";
            this.checkBoxHideInternal.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_CheckBoxHideInternal);
            // 
            // buttonCreateCustomDocumentProperty
            // 
            this.buttonCreateCustomDocumentProperty.Label = "Create Custom Document Property";
            this.buttonCreateCustomDocumentProperty.Name = "buttonCreateCustomDocumentProperty";
            this.buttonCreateCustomDocumentProperty.OfficeImageId = "PropertyInsert";
            this.buttonCreateCustomDocumentProperty.ShowImage = true;
            this.buttonCreateCustomDocumentProperty.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonCreateCustomDocumentProperty);
            // 
            // buttonBindCustomXMLPart
            // 
            this.buttonBindCustomXMLPart.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.buttonBindCustomXMLPart.Label = "Bind XML";
            this.buttonBindCustomXMLPart.Name = "buttonBindCustomXMLPart";
            this.buttonBindCustomXMLPart.ShowImage = true;
            this.buttonBindCustomXMLPart.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonBindCustomXMLPart);
            // 
            // groupView
            // 
            this.groupView.Items.Add(this.dropDownFieldShading);
            this.groupView.Items.Add(this.toggleButtonShowFieldShading);
            this.groupView.Items.Add(this.toggleButtonShowFieldCodes);
            this.groupView.Label = "View";
            this.groupView.Name = "groupView";
            // 
            // dropDownFieldShading
            // 
            ribbonDropDownItemImpl1.Label = "Never";
            ribbonDropDownItemImpl1.Tag = "0";
            ribbonDropDownItemImpl2.Label = "Always";
            ribbonDropDownItemImpl2.Tag = "1";
            ribbonDropDownItemImpl3.Label = "When Selected";
            ribbonDropDownItemImpl3.Tag = "2";
            this.dropDownFieldShading.Items.Add(ribbonDropDownItemImpl1);
            this.dropDownFieldShading.Items.Add(ribbonDropDownItemImpl2);
            this.dropDownFieldShading.Items.Add(ribbonDropDownItemImpl3);
            this.dropDownFieldShading.Label = "Field Shading";
            this.dropDownFieldShading.Name = "dropDownFieldShading";
            this.dropDownFieldShading.OfficeImageId = "FieldShading";
            this.dropDownFieldShading.ShowImage = true;
            this.dropDownFieldShading.ShowItemImage = false;
            this.dropDownFieldShading.SelectionChanged += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnSelectionChanged_DropDownFieldShading);
            // 
            // toggleButtonShowFieldShading
            // 
            this.toggleButtonShowFieldShading.Label = "Form Field Shading";
            this.toggleButtonShowFieldShading.Name = "toggleButtonShowFieldShading";
            this.toggleButtonShowFieldShading.OfficeImageId = "FieldShading";
            this.toggleButtonShowFieldShading.ScreenTip = "Show Form Field Shading";
            this.toggleButtonShowFieldShading.ShowImage = true;
            this.toggleButtonShowFieldShading.SuperTip = "Show Form Field Shading";
            this.toggleButtonShowFieldShading.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonShowFieldShading);
            // 
            // toggleButtonShowFieldCodes
            // 
            this.toggleButtonShowFieldCodes.Label = "Field Codes";
            this.toggleButtonShowFieldCodes.Name = "toggleButtonShowFieldCodes";
            this.toggleButtonShowFieldCodes.OfficeImageId = "FieldCodes";
            this.toggleButtonShowFieldCodes.ScreenTip = "Show Field Codes";
            this.toggleButtonShowFieldCodes.ShowImage = true;
            this.toggleButtonShowFieldCodes.SuperTip = "Show Field Codes";
            this.toggleButtonShowFieldCodes.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ToggleButtonShowFieldCodes);
            // 
            // groupMiscellaneous
            // 
            this.groupMiscellaneous.Items.Add(this.toggleButtonShowMessagesForm);
            this.groupMiscellaneous.Items.Add(this.buttonShowAboutForm);
            this.groupMiscellaneous.Items.Add(this.buttonShowHelpForm);
            this.groupMiscellaneous.Items.Add(this.buttonShowConfigurationForm);
            this.groupMiscellaneous.Label = "Miscellaneous";
            this.groupMiscellaneous.Name = "groupMiscellaneous";
            // 
            // buttonShowAboutForm
            // 
            this.buttonShowAboutForm.Label = "About";
            this.buttonShowAboutForm.Name = "buttonShowAboutForm";
            this.buttonShowAboutForm.OfficeImageId = "FileProperties";
            this.buttonShowAboutForm.ShowImage = true;
            this.buttonShowAboutForm.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonShowAboutForm);
            // 
            // buttonShowHelpForm
            // 
            this.buttonShowHelpForm.Label = "Help";
            this.buttonShowHelpForm.Name = "buttonShowHelpForm";
            this.buttonShowHelpForm.OfficeImageId = "WorkflowPending";
            this.buttonShowHelpForm.ShowImage = true;
            this.buttonShowHelpForm.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonShowHelpForm);
            // 
            // buttonShowConfigurationForm
            // 
            this.buttonShowConfigurationForm.Label = "Configuration";
            this.buttonShowConfigurationForm.Name = "buttonShowConfigurationForm";
            this.buttonShowConfigurationForm.OfficeImageId = "ControlsGallery";
            this.buttonShowConfigurationForm.ShowImage = true;
            this.buttonShowConfigurationForm.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.OnClick_ButtonShowConfigurationForm);
            // 
            // Ribbon
            // 
            this.Name = "Ribbon";
            this.RibbonType = "Microsoft.Word.Document";
            this.Tabs.Add(this.tabComponentBasedAuthoring);
            this.Load += new Microsoft.Office.Tools.Ribbon.RibbonUIEventHandler(this.OnLoad);
            this.tabComponentBasedAuthoring.ResumeLayout(false);
            this.tabComponentBasedAuthoring.PerformLayout();
            this.groupReferences.ResumeLayout(false);
            this.groupReferences.PerformLayout();
            this.groupTools.ResumeLayout(false);
            this.groupTools.PerformLayout();
            this.groupFields.ResumeLayout(false);
            this.groupFields.PerformLayout();
            this.groupDocumentProperties.ResumeLayout(false);
            this.groupDocumentProperties.PerformLayout();
            this.box.ResumeLayout(false);
            this.box.PerformLayout();
            this.groupView.ResumeLayout(false);
            this.groupView.PerformLayout();
            this.groupMiscellaneous.ResumeLayout(false);
            this.groupMiscellaneous.PerformLayout();

        }

        #endregion

        internal Microsoft.Office.Tools.Ribbon.RibbonTab tabComponentBasedAuthoring;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupReferences;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonCreateCustomDocumentProperty;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonUpdateFromSource;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonUpdateToSource;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupDocumentProperties;
        internal Microsoft.Office.Tools.Ribbon.RibbonDropDown dropDownCustomDocumentProperties;
        internal Microsoft.Office.Tools.Ribbon.RibbonCheckBox checkBoxHideInternal;
        internal Microsoft.Office.Tools.Ribbon.RibbonSplitButton splitButtonInclude;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonIncludeText;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonIncludePicture;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonIncludeObject;
        internal Microsoft.Office.Tools.Ribbon.RibbonBox box;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonOpenSourceFile;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupFields;
        internal Microsoft.Office.Tools.Ribbon.RibbonSplitButton splitButtonFieldInsert;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertEmptyField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertDateField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertTimeField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertListNumField;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonInsertPageField;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupMiscellaneous;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonShowAboutForm;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton buttonShowHelpForm;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton toggleButtonShowFieldCodes;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton toggleButtonShowFieldShading;
        internal Microsoft.Office.Tools.Ribbon.RibbonDropDown dropDownFieldShading;
        internal RibbonSeparator separatorFirst;
        internal RibbonSeparator separatorSecond;
        internal RibbonButton buttonCheckReferences;
        internal RibbonSplitButton splitButtonFieldAction;
        internal RibbonButton buttonFieldUpdate;
        internal RibbonToggleButton toggleButtonFieldLock;
        internal RibbonToggleButton toggleButtonShowFieldCode;
        internal RibbonSplitButton splitButtonFieldFormat;
        internal RibbonSplitButton splitButtonFieldFormatCapitalization;
        internal RibbonToggleButton toggleButtonFieldFormatCaps;
        internal RibbonToggleButton toggleButtonFieldFormatFirstCap;
        internal RibbonToggleButton toggleButtonFieldFormatUpper;
        internal RibbonToggleButton toggleButtonFieldFormatLower;
        internal RibbonButton buttonShowConfigurationForm;
        internal RibbonButton buttonBindCustomXMLPart;
        internal RibbonGroup groupView;
        internal RibbonSplitButton splitButtonFieldFormatNumber;
        internal RibbonToggleButton toggleButtonFieldFormatAlphabetic;
        internal RibbonToggleButton toggleButtonFieldFormatArabic;
        internal RibbonToggleButton toggleButtonFieldFormatCardText;
        internal RibbonToggleButton toggleButtonFieldFormatDollarText;
        internal RibbonToggleButton toggleButtonFieldFormatHex;
        internal RibbonToggleButton toggleButtonFieldFormatOrdText;
        internal RibbonToggleButton toggleButtonFieldFormatOrdinal;
        internal RibbonToggleButton toggleButtonFieldFormatRoman;
        internal RibbonToggleButton toggleButtonFieldFormatMergeFormat;
        internal RibbonButton buttonCompareDocuments;
        internal RibbonGroup groupTools;
        internal RibbonToggleButton toggleButtonShowMessagesForm;
    }

    /// <summary>
    /// The class <see cref="ThisRibbonCollection"/> contains all ribbons of the
    /// application.
    /// </summary>
    partial class ThisRibbonCollection
    {
        /// <summary>
        /// Gets the ribbon.
        /// </summary>
        internal Ribbon ThisRibbon
        {
            get { return this.GetRibbon<Ribbon>(); }
        }
    }
}
